In [206]:
import numpy as np
import scipy as sp

from tenpy.networks.site import SpinSite
import tenpy.linalg.np_conserved as npc
import tenpy

In [207]:
site_v = SpinSite(S=0.5, conserve="Sz")
leg_v = site_v.onsite_ops['Sz'].legs[0]

site_p = SpinSite(S=1, conserve="Sz")
leg_p = site_p.onsite_ops['Sz'].legs[0]

B = npc.zeros([leg_v, leg_p.conj(), leg_v.conj()], labels=['vL', 'p', 'vR'])  

In [208]:
B[:,0,:] = np.array([[0, np.sqrt(2/3)],[0,0]])
B[:,1,:] = np.array([[-np.sqrt(1/3), 0],[0,np.sqrt(1/3)]])
B[:,2,:] = np.array([[0, 0],[-np.sqrt(2/3),0]])

In [209]:
print(B)

<npc.Array shape=(2, 3, 2) labels=['vL', 'p', 'vR']
charge=ChargeInfo([1], ['2*Sz'])
 +1     | -1     | -1     
0 [[-1] |0 [[-2] |0 [[-1] 
1  [ 1]]|1  [ 0] |1  [ 1]]
2       |2  [ 2]]|2       
        |3       |        
[[[ 0.          0.81649658]
  [-0.57735027  0.        ]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [ 0.          0.57735027]
  [-0.81649658  0.        ]]]
>


In [193]:
N = 2

B0 = B.copy()
B0.ireplace_labels(['vL','p','vR'],['vL0','p0','vR0'])
for ind in range(N):
    B0 = npc.tensordot(B0,B,axes=('vR0', 'vL'))
    B0 = B0.combine_legs([['p0', 'p']], qconj=-1)
    B0.ireplace_labels(['(p0.p)','vR'],['p0','vR0'])


In [194]:
B0[0,:,0].to_ndarray() + B0[1,:,1].to_ndarray()

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.38490018,  0.38490018,  0.38490018,  0.        , -0.38490018,
       -0.38490018,  0.38490018,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ])

In [2]:
import numpy as np
A = {}
A[0] = np.array([[0, np.sqrt(2/3)],[0,0]])
A[1] = np.array([[-np.sqrt(1/3), 0],[0,np.sqrt(1/3)]])
A[2] = np.array([[0, 0],[-np.sqrt(2/3),0]])


In [4]:
vals = []
for i in range(0,3):
    for j in range(0,3):
        for k in range(0,3):
            vals.append(np.trace(A[i]@A[j]@A[k]))
norm = np.sum( np.array(vals)**2 )

In [5]:
vals

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -0.3849001794597505,
 0.0,
 0.38490017945975047,
 0.0,
 0.0,
 0.0,
 0.3849001794597505,
 0.0,
 0.0,
 0.0,
 -0.3849001794597505,
 0.0,
 0.0,
 0.0,
 -0.38490017945975047,
 0.0,
 0.3849001794597505,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [6]:
counter = 0
Tt = {}
for i in range(0,3):
    for j in range(0,3):
        Tt[counter] = np.kron(A[i],A[j].conj())
        counter +=1

In [12]:
Tt

{0: array([[0.        , 0.        , 0.        , 0.66666667],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ]]),
 1: array([[-0.        ,  0.        , -0.47140452,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.47140452],
        [-0.        ,  0.        , -0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]),
 2: array([[ 0.        ,  0.        ,  0.        ,  0.        ],
        [-0.        ,  0.        , -0.66666667,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [-0.        ,  0.        , -0.        ,  0.        ]]),
 3: array([[-0.        , -0.47140452,  0.        ,  0.        ],
        [-0.        , -0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.47140452],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]),
 4: 

In [8]:
# Projection to S=1 subspace
P = np.zeros((3,9))
P[0,1] = -1/np.sqrt(2)
P[0,3] = 1/np.sqrt(2)

P[1,2] = -1/np.sqrt(2)
P[1,6] = 1/np.sqrt(2)

P[2,5] = -1/np.sqrt(2)
P[2,7] = 1/np.sqrt(2)

In [9]:
P

array([[ 0.        , -0.70710678,  0.        ,  0.70710678,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.70710678,  0.        ,  0.        ,
         0.        ,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -0.70710678,  0.        ,  0.70710678,  0.        ]])

In [60]:
# # Projection to S=2 subspace
# P = np.zeros((5,9))
# P[0,0] = 1
# P[4,8] = 1

# P[1,1] = 1/np.sqrt(2)
# P[1,3] = 1/np.sqrt(2)

# P[4,7] = 1/np.sqrt(2)
# P[3,5] = 1/np.sqrt(2)

# P[2,2] = 1/np.sqrt(6)
# P[2,4] = 2/np.sqrt(6)
# P[2,6] = 1/np.sqrt(6)

In [10]:
Nt = {}
for i in range(0,P.shape[0]):
    Nt[i] = np.zeros(Tt[0].shape)
    for j in range(0,P.shape[1]):
        Nt[i] = Nt[i] + P[i,j]*Tt[j]

In [11]:
Nt

{0: array([[ 0.        , -0.33333333,  0.33333333,  0.        ],
        [ 0.        ,  0.        ,  0.        , -0.33333333],
        [ 0.        ,  0.        ,  0.        ,  0.33333333],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]),
 1: array([[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.47140452,  0.        ],
        [ 0.        , -0.47140452,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]),
 2: array([[ 0.        ,  0.        ,  0.        ,  0.        ],
        [-0.33333333,  0.        ,  0.        ,  0.        ],
        [ 0.33333333,  0.        ,  0.        ,  0.        ],
        [ 0.        , -0.33333333,  0.33333333,  0.        ]])}

In [201]:
for i in range(P.shape[0]):
    print(i)
    print(Nt[i])
    print()

0
[[ 0.         -0.33333333  0.33333333  0.        ]
 [ 0.          0.          0.         -0.33333333]
 [ 0.          0.          0.          0.33333333]
 [ 0.          0.          0.          0.        ]]

1
[[ 0.          0.          0.          0.        ]
 [ 0.          0.          0.47140452  0.        ]
 [ 0.         -0.47140452  0.          0.        ]
 [ 0.          0.          0.          0.        ]]

2
[[ 0.          0.          0.          0.        ]
 [-0.33333333  0.          0.          0.        ]
 [ 0.33333333  0.          0.          0.        ]
 [ 0.         -0.33333333  0.33333333  0.        ]]



In [76]:
counter = 0
vals = []
for i in range(0,3):
    for j in range(0,3):
        for k in range(0,3):
            for l in range(0,3):
                vals.append(np.trace(Nt[i]@Nt[j]@Nt[k]@Nt[l]))

vals

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.04938271604938271,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -0.04938271604938269,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.09876543209876543,
 0.0,
 -0.0493827160493827,
 0.0,
 0.04938271604938271,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -0.04938271604938269,
 0.0,
 0.0,
 0.0,
 -0.04938271604938269,
 0.0,
 0.09876543209876537,
 0.0,
 -0.04938271604938269,
 0.0,
 0.0,
 0.0,
 -0.04938271604938269,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.04938271604938271,
 0.0,
 -0.0493827160493827,
 0.0,
 0.09876543209876543,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -0.04938271604938269,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.04938271604938271,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [80]:
np.sum( np.array(vals)**2 )

0.058527663465935034

In [86]:
counter = 0
vals = []
for i in range(0,3):
    for j in range(0,3):
        vals.append(np.trace(Nt[i]@Nt[j]))
norm = np.sum( np.array(vals)**2 )

In [87]:
vals

[0.0,
 0.0,
 0.4444444444444444,
 0.0,
 -0.4444444444444443,
 0.0,
 0.4444444444444444,
 0.0,
 0.0]

In [85]:
norm**2

0.35116598079561023

In [13]:
E = {}
for i in range(0,P.shape[0]):
    E[i] = np.kron(Nt[i],Nt[i].conj())

In [26]:
# the bug is corrected here

Etot = np.zeros(E[0].shape)
for val in E:
    Etot = Etot + E[val]

evals, evecs = np.linalg.eig(Etot)

In [29]:
np.sort(evals)

array([-3.84900179e-01+0.00000000e+00j, -2.22222222e-01+0.00000000e+00j,
       -2.22222222e-01+0.00000000e+00j, -2.22222222e-01+0.00000000e+00j,
       -5.53284821e-18+0.00000000e+00j, -2.25789756e-18+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        8.56253657e-19-5.67811901e-18j,  8.56253657e-19+5.67811901e-18j,
        1.38661644e-17+0.00000000e+00j,  4.16604685e-17+0.00000000e+00j,
        2.22222222e-01+0.00000000e+00j,  2.22222222e-01+0.00000000e+00j,
        2.22222222e-01+0.00000000e+00j,  3.84900179e-01+0.00000000e+00j])

In [10]:
L = 10
norm = np.trace( np.linalg.matrix_power(Etot,L) )

vals = np.zeros((9,9))
for i in range(0,9):
    for j in range(0,9):        
        vals[i,j] = np.trace(np.kron(Tt[i],np.conj(Tt[j]) )@np.linalg.matrix_power(Etot,L-2))/norm

In [11]:
p = np.linalg.eigvals(vals)
p = p + 1e-10
np.sum(-p*np.log(p))

1.3688674012155009

In [12]:
np.log(4)

1.3862943611198906

In [13]:
counter = 0
Tt = {}
for i in range(0,3):
    for j in range(0,3):
        for k in range(0,3):    
            Tt[counter] = A[i]@A[j]@A[k]
            counter +=1
        
L = 20
norm = np.trace( np.linalg.matrix_power(Etot,L) )

vals = np.zeros((27,27))
for i in range(0,27):
    for j in range(0,27):        
        vals[i,j] = np.trace(np.kron(Tt[i],np.conj(Tt[j]) )@np.linalg.matrix_power(Etot,L-3))/norm

In [14]:
p = np.linalg.eigvals(vals)
p = p + 1e-10
np.sum(-p*np.log(p))

(1.384182475866883+0j)

In [15]:
counter = 0
Tt = {}
for i in range(0,3):
    for j in range(0,3):
        for k in range(0,3):    
            for l in range(0,3):    
                Tt[counter] = A[i]@A[j]@A[k]@A[l]
                counter +=1
        
L = 20
norm = np.trace( np.linalg.matrix_power(Etot,L) )

vals = np.zeros((81,81))
for i in range(0,81):
    for j in range(0,81):        
        vals[i,j] = np.trace(np.kron(Tt[i],np.conj(Tt[j]) )@np.linalg.matrix_power(Etot,L-3))/norm

In [16]:
p = np.linalg.eigvals(vals)
p = p + 1e-10
np.sum(-p*np.log(p))

(1.386067756597733-2.465190328815662e-32j)

In [17]:
L = 5
norm = np.trace( np.linalg.matrix_power(Etot,L) )

vals = np.zeros((3,3))

for i in range(0,3):
    for j in range(0,3):
        vals[i,j] = np.trace(E[i]@E[j]@np.linalg.matrix_power(Etot,L-2))/norm

In [18]:
vals

array([[0.        , 0.11666667, 0.21666667],
       [0.11666667, 0.1       , 0.11666667],
       [0.21666667, 0.11666667, 0.        ]])

In [19]:
np.sum(-vals*np.log(vals))

/var/folders/9x/26psv69j0_z6sl02w55fn8nr0000gp/T/ipykernel_33297/1944748104.py:1: RuntimeWarning: divide by zero encountered in log
  np.sum(-vals*np.log(vals))
/var/folders/9x/26psv69j0_z6sl02w55fn8nr0000gp/T/ipykernel_33297/1944748104.py:1: RuntimeWarning: invalid value encountered in multiply
  np.sum(-vals*np.log(vals))


nan

In [20]:
np.log(4)

1.3862943611198906

In [21]:
vals

array([[0.        , 0.11666667, 0.21666667],
       [0.11666667, 0.1       , 0.11666667],
       [0.21666667, 0.11666667, 0.        ]])

In [22]:
Sx = np.array([[0,1,0],[1,0,1],[0,1,0]])/np.sqrt(2)
Sz = np.array([[1,0,0],[0,0,0],[0,0,-1]])

In [23]:

np.round( sp.linalg.expm(1j*np.pi*Sx), 4)

AttributeError: module 'scipy' has no attribute 'linalg'

In [ ]:
np.round( sp.linalg.expm(1j*np.pi*Sz), 4)